import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/ui/header/header";
import Footer from "@/components/ui/footer/footer";
import { AuthProvider } from "@/context/auth-context";
import { CoinDataProvider } from "@/context/coin-data-context";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-gray-200 text-black`}
      >
        <NextIntlClientProvider messages={messages}>
          <AuthProvider>
            <Header></Header>
            <CoinDataProvider>
              <div className="pt-16 min-h-[100vh]">{children}</div>
            </CoinDataProvider>
          </AuthProvider>
        </NextIntlClientProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
